---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-manager-certificate
spec:
  secretName: mongodb-tls
  issuerRef:
    name: ca-issuer
    kind: Issuer
  commonName: "*.mongodb-svc.default.svc.cluster.local"
  dnsNames:
  - "*.mongodb-svc.default.svc.cluster.local"
  - "mongodb-0.mongodb-svc.default.svc.cluster.local"
  - "mongodb-1.mongodb-svc.default.svc.cluster.local"
  - "mongodb-2.mongodb-svc.default.svc.cluster.local"
  - "localhost"
